### ISSUE TITLE
video-editor-inital

### ISSUE THREAD

**Issue by Kneesal** [JesusFilm/core#4499]
Notes for QA

**Comment by jahhun** [comment]
<img src="https://uploads.linear.app/c59e546a-d270-47fe-8c65-0d5513467418/115a3bec-b80b-4536-90ca-02ae3ab0f418/509f9393-632b-43b9-8950-1efae217e420?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2M1OWU1NDZhLWQyNzAtNDdmZS04YzY1LTBkNTUxMzQ2NzQxOC8xMTVhM2JlYy1iODBiLTQ1MzYtOTBjYS0wMmFlM2FiMGY0MTgvNTA5ZjkzOTMtNjMyYi00M2I5LTg5NTAtMWVmYWUyMTdlNDIwIiwiaWF0IjoxNzMyNTkwNjYxLCJleHAiOjMzMzAzMTUwNjYxfQ.jg-wUEjSzAkrAfghWz76ug3zgDrxqqBJeHF2ucojyu0 " alt="image.png" width="1920" height="1080" />
